linters:
  disable-all: true
  enable:
    # - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    - gofumpt
    - goimports
    # - gci
    - misspell
    - unconvert
    - usestdlibvars
    # - exhaustive

linters-settings:
  staticcheck:
    go: "1.21"
  goimports:
    local-prefixes: github.com/clash-dev/clash
